replicaCount: 1

pullPolicy: Always

deployment:
  name: consumer

service:
  name: consumer
  port: 9997
  targetPort: 9997
  nodePort: 30002
  type: NodePort

configMap:
  name: consumer

applicationProperties:
  mountPath: "/config/application.properties"
  subPath: application.properties
