replicaCount: 1

pullPolicy: Always

deployment:
  name: producer

service:
  name: producer
  port: 9999
  targetPort: 9999
  nodePort: 30000
  type: NodePort

configMap:
  name: producer

applicationProperties:
  mountPath: "/config/application.properties"
  subPath: application.properties
