apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.name }}
    group: {{ .Values.global.group }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.global.image.secret }}
      containers:
        - name: {{ .Values.deployment.name }}
          image: {{ .Values.global.image.repository }}/{{ .Values.deployment.name }}:{{ .Values.deployment.image.tag }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          args: ["java", "-jar", {{ .Values.deployment.name }}.jar]
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - secretRef:
                name: {{ .Values.global.secret }}
            - configMapRef:
                name: {{ .Values.global.data }}
          volumeMounts:
            - name: appconfig
              mountPath: {{ .Values.applicationProperties.mountPath }}
              subPath: {{ .Values.applicationProperties.subPath }}
      volumes:
        - name: appconfig
          configMap:
            name: {{ .Values.configMap.name }}